server:
  port: ":8081"
  mode: "release"

database:
  username: "postgres"
  password: "zyz20050922"
  host: "192.168.3.114"
  port: 5432
  dbname: "graduation_project"
  charset: "utf8mb4"

oss:
  access_key_id: "0CsZkaRGG_4IifjzH4NOcMN4jGbngAoNoZBK7rsQ"
  secret_access_key: "S3flntD41AG3rS75BdcRR3Yrb-Y_PxIjRgvFT7W1"
  bucket: "sleet"
  endpoint: "https://s3-cn-east-1.qiniucs.com"
  base_path: ""
  cdn_domain: "http://cdn.gelsomino.cn"

jwt:
  secret_key: "89$kL789&*pO0987654321qWERTYuiop[]{}|;:,.<>?/!@#$%^&*()_+"
  access_token_expire_seconds: 86400
  refresh_token_expire_seconds: 2592000

rtc:
  app_id: "69de80fd8770340178b8e840"
  app_key: "6076c0daf2ca4d4cb8ef6132e9b1767f"
  token_expire_seconds: 7200

log:
  level: "info"
  filename: "logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

redis:
  addr: "192.168.3.114"
  port: 6379
  password: ""
  db: 0
